using Microsoft.EntityFrameworkCore.Migrations;

namespace KanbanBoard.Services.IdentityServer.Data.Migrations
{
    public partial class InitialWithAutoGenerated : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
